package edu.harvard.data.canvas.cli;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.ExecutorService;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.kohsuke.args4j.Argument;

import edu.harvard.data.DataConfigurationException;
import edu.harvard.data.DumpInfo;
import edu.harvard.data.ReturnStatus;
import edu.harvard.data.canvas.CanvasDataConfig;
import edu.harvard.data.canvas.data_api.ApiClient;
import edu.harvard.data.canvas.data_api.CanvasDataSchema;
import edu.harvard.data.schema.SchemaDifference;
import edu.harvard.data.schema.UnexpectedApiResponseException;

public class CompareSchemasCommand implements Command {

  private static final Logger log = LogManager.getLogger();

  @Argument(index = 0, usage = "UUID for the dump, generated by the Canvas Data API.", metaVar = "uuid", required = true)
  private String dumpId;

  @Argument(index = 1, usage = "Expected schema version.", metaVar = "1.0.0", required = true)
  private String expectedVersion;

  @Override
  public ReturnStatus execute(final CanvasDataConfig config, final ExecutorService exec)
      throws IOException, DataConfigurationException, UnexpectedApiResponseException {
    final ApiClient api = new ApiClient(config.getCanvasDataHost(),
        config.getCanvasApiKey(), config.getCanvasApiSecret());
    final DumpInfo info = DumpInfo.find(dumpId);

    if (expectedVersion.equals(info.getSchemaVersion())) {
      log.info("Schema version numbers match.");
      return ReturnStatus.OK;
    }
    final CanvasDataSchema schema1 = (CanvasDataSchema) api.getSchema(expectedVersion);
    final CanvasDataSchema schema2 = (CanvasDataSchema) api.getSchema(info.getSchemaVersion());
    final List<SchemaDifference> differences = schema1.diff(schema2);
    if (differences.isEmpty()) {
      log.info("Schemas are identical.");
      return ReturnStatus.OK;
    }

    for (final SchemaDifference difference : differences) {
      if (difference.getField() == null || !difference.getField().equals("description")) {
        log.warn("Schema difference: " + difference);
      }
    }
    return ReturnStatus.VERIFICATION_FAILURE;
  }

  @Override
  public String getDescription() {
    return "Compare two versions of the Canvas Data schema.";
  }

}
