package edu.harvard.data.canvas.cli;

import java.io.IOException;
import java.util.concurrent.ExecutorService;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.kohsuke.args4j.Argument;
import org.kohsuke.args4j.Option;

import edu.harvard.data.AwsUtils;
import edu.harvard.data.DataConfiguration;
import edu.harvard.data.DataConfigurationException;
import edu.harvard.data.FormatLibrary;
import edu.harvard.data.ReturnStatus;
import edu.harvard.data.TableFormat;
import edu.harvard.data.VerificationException;
import edu.harvard.data.Verifier;
import edu.harvard.data.canvas.phase_0.Phase0PostVerifier;
import edu.harvard.data.canvas.phase_1.Phase1PostVerifier;
import edu.harvard.data.canvas.phase_2.Phase2PostVerifier;
import edu.harvard.data.canvas.phase_3.Phase3PostVerifier;
import edu.harvard.data.schema.UnexpectedApiResponseException;

public class PostVerifyCommand implements Command {

  private static final Logger log = LogManager.getLogger();

  @Argument(index = 0, usage = "Verification phase.", metaVar = "0", required = true)
  public int phase;

  @Option(name = "-i", usage = "UUID for the dump, generated by the Canvas Data API. Required for phase 0.", metaVar = "uuid", required = false)
  public String dumpId;

  @Option(name = "-in", usage = "Location of data files. Required for phases > 0.", metaVar = "hdfs://path/to/data", required = false)
  public String dataDir;

  @Override
  public ReturnStatus execute(final DataConfiguration config, final ExecutorService exec)
      throws IOException, DataConfigurationException, UnexpectedApiResponseException,
      ArgumentError {
    if (!checkArguments()) {
      return ReturnStatus.ARGUMENT_ERROR;
    }
    try {
      final Verifier verifier = getVerifier(config, exec);
      verifier.verify();
    } catch (final VerificationException e) {
      log.error("Verification Exception", e);
      return ReturnStatus.VERIFICATION_FAILURE;
    }
    return ReturnStatus.OK;
  }

  private Verifier getVerifier(final DataConfiguration config, final ExecutorService exec)
      throws ArgumentError {
    final AwsUtils aws = new AwsUtils();
    final FormatLibrary formats = new FormatLibrary();
    final TableFormat format = formats.getFormat(FormatLibrary.Format.CanvasDataFlatFiles);
    switch (phase) {
    case 0:
      return new Phase0PostVerifier(dumpId, aws, format, config.getScratchDir(), exec);
    case 1:
      return new Phase1PostVerifier();
    case 2:
      return new Phase2PostVerifier();
    case 3:
      return new Phase3PostVerifier();
    }
    throw new ArgumentError("Invalid phase " + phase);
  }

  private boolean checkArguments() {
    if (phase == 0) {
      if (dumpId == null) {
        log.error("Dump ID is required for Phase 0");
        return false;
      }
    } else {
      if (dataDir == null) {
        log.error("Data directory is required for all phases other than zero.");
        return false;
      }
    }
    return true;
  }

  @Override
  public String getDescription() {
    return "Perform verification operations following a phase.";
  }

}
